#!/bin/sh
EXTERNAL_LINK=${1:-eth0}
UE_SUBNET="10.255.0.0/24"
QCORE_TUN=qcoretun

# Enable IPv4 forwarding
sudo sysctl -w net.ipv4.ip_forward=1               

# Create the veth pair veth0-veth1 to represent the UE network.
# QCore will add /32 routes to UEs on veth0. 
sudo ip link add veth0 type veth peer veth1
sudo ip link set up veth0
sudo ip link set up veth1
sudo ip link set arp off dev veth0
sudo ethtool -K veth0 rx off tx off # Disable checksum offload - otherwise TCP will break

# Create a tun device to inject both UE and GTP packets into Linux routing.
sudo ip tuntap add mode tun user $(whoami) name $QCORE_TUN 
sudo ip link set $QCORE_TUN up 
sudo iptables -A FORWARD -i $QCORE_TUN -j ACCEPT           

# The following gives full flexibility in packet injection. 
# - Disable reverse path filtering on tun interface so that QCore can inject UE or GTP packets.
# - Allow QCore to have a loopback GTP address.
# - Allow the RAN to have a loopback GTP address.
sudo sysctl -w net.ipv4.conf.$QCORE_TUN.rp_filter=0   
sudo sysctl -w net.ipv4.conf.all.rp_filter=0
sudo sysctl -w net.ipv4.conf.$QCORE_TUN.accept_local=1     
sudo sysctl -w net.ipv4.conf.$QCORE_TUN.route_localnet=1

#---------- UEs on LAN (DHCP, no NAT) ------------------
# Enable proxy ARP. 
sudo sysctl -w net.ipv4.conf.$EXTERNAL_LINK.proxy_arp=1

#---------- UEs on separate network (no DHCP, UPF NAT) ------------------
# Allow UE packets to flow over the external link to the outside world.
# Enable NAT on the way out and accept them on the way back in
sudo iptables -t nat -A POSTROUTING -o $EXTERNAL_LINK -s $UE_SUBNET -j MASQUERADE
sudo iptables -A FORWARD -i $EXTERNAL_LINK -j ACCEPT -d $UE_SUBNET

#---------- Extra links for testing ------------------
# For testing with mock DHCP server, or multiple qcores on a single machine.
# This section is not needed to run a single live instance of QCore.
sudo ip link add veth2 type veth peer veth3
sudo ip link set veth2 up
sudo ip link set veth3 up
sudo ip addr add 10.255.0.1/24 dev veth2
sudo ip addr add 10.255.0.200/24 dev veth2
sudo ip addr add 10.255.0.201/24 dev veth2
sudo sysctl -w net.ipv4.conf.veth2.proxy_arp=1
sudo ip tuntap add mode tun user $(whoami) name qcoretun2 
sudo ip link set qcoretun2 up 
sudo iptables -A FORWARD -i qcoretun2 -j ACCEPT

# Set up Ethernet links - required for integration tests to pass
./setup-ethernet


