# This file contains a list of SIM credentials in the form
# [imsi-<IMSI>]
# ki = "<KI>"
# opc = "<OPC>"
#
# The IMSI is a string of decimal digits that identifies a mobile subscriber.
# The KI + OPC are the secret credentials that are burnt into the SIM card, as a hex string.
[imsi-123450123456789]
ki = "0123456789abcdef0123456789abcdef"
opc = "0123456789abcdef0123456789abcdef"
