[package]
name = "security"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8.4"
cmac = "0.7.2"
hex-literal = "1.0.0"
milenage = "0.1.4"
rand = "0.9.0"
hmac = "0.12.1"
sha2 = "0.10.8"
rand_core = { version = "0.9.3", features = ["os_rng"] }
